hostname = "localhost:7878"

[oauth2.discord]
enabled = true
authorize_url = "https://discord.com/oauth2/authorize"
token_url = "https://discord.com/api/oauth2/token"
client_id = "{{DISCORD_CLIENT_ID}}"
redirect_uri = "https://localhost:12345/auth/oauth2-redirect/discord"
secret = "{{DISCORD_SECRET}}"
scope = "identify"

[oauth2.microsoft]
enabled = true
authorize_url = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
token_url = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
client_id = "{{MICROSOFT_CLIENT_ID}}"
redirect_uri = "https://localhost:12345/auth/oauth2-redirect/microsoft"
secret = "{{MICROSOFT_SECRET}}"
scope = "User.Read offline_access"
