hostname = "localhost:7878"
dev_mode = false

[score]
max_reward = 200
exponent = 0.75
divider = 1440

[oauth2.discord]
enabled = true
authorize_url = "https://discord.com/oauth2/authorize"
token_url = "https://discord.com/api/oauth2/token"
user_info_url = "https://discord.com/api/v10/users/@me"
client_id = "{{CLIENT_ID}}"
redirect_uri = "https://localhost:12345/auth/oauth2-redirect/discord"
secret = "{{CLIENT_SECRET}}"
scope = "identify"

[oauth2.github]
enabled = true
authorize_url = "https://github.com/login/oauth/authorize"
token_url = "https://github.com/login/oauth/access_token"
user_info_url = "https://api.github.com/user"
client_id = "{{CLIENT_ID}}"
redirect_uri = "https://localhost:12345/auth/oauth2-redirect/github"
secret = "{{CLIENT_SECRET}}"
scope = "user"

[oauth2.microsoft]
enabled = true
authorize_url = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
token_url = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
user_info_url = "https://graph.microsoft.com/v1.0/me"
client_id = "{{CLIENT_ID}}"
redirect_uri = "https://localhost:12345/auth/oauth2-redirect/microsoft"
secret = "{{CLIENT_SECRET}}"
scope = "User.Read offline_access"
